# Generated by Django 4.2.6 on 2023-10-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoCut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="videos/")),
                ("start_time", models.CharField(max_length=8)),
                ("end_time", models.CharField(max_length=8)),
            ],
        ),
    ]
