# Generated by Django 4.2.6 on 2023-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_cutter_app", "0003_videocut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videocut",
            name="video",
            field=models.FileField(upload_to="videos/"),
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
