# Generated by Django 4.2.6 on 2023-10-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_cutter_app", "0004_alter_videocut_video_delete_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="videos/")),
            ],
        ),
        migrations.DeleteModel(
            name="VideoCut",
        ),
    ]
