# Generated by Django 4.2.6 on 2023-10-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_cutter_app", "0006_videocut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videocut",
            name="video_path",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
